---
title: "AHD attendance"
author: "tmikami"
date: "2022-12-05"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
if (!require("pacman")) { install.packages("pacman") }
pacman::p_load( pipeR, dplyr, tidyverse, pdftools, tabulizer, data.table, lubridate, knitr, kableExtra, gt )
if (!require("remotes")) { install.packages("remotes") }
```

## Rotation table

```{r Rotation table}
home_path = "/Users/TakahisaMikami/drive/0.NeuroEducation/Tufts_education/AHD/AHD_participants"
df_rotation = openxlsx::read.xlsx(file.path(home_path, "attendance_reports/participants_schedule.xlsx"))
df_rotation %>>% 
  kbl() %>%
  kable_paper("hover", full_width = F)
  # kable_styling()

```

## Attendance reports

```{r Attendance reports}
date_list <- c("d1104", "d1111", "d1118", "d1202") # , "d1209"
path_prefix <- paste0(home_path, "/attendance_reports/participants_")
file_list <- paste0(path_prefix, date_list, ".csv") %>>% as.list()

# Take a look at the first 10 rows in the first file 
data.table::fread( file_list[[1]] ) %>>% 
    dplyr::select( name = 1, t_join = 3, t_leave = 4 ) %>>%
  head(10) %>>% 
  # gt()
  kbl() %>%
  kable_paper(c("striped", "hover", "condensed", "responsive"), full_width = F)

```

```{r Creating functions}
# Converting names
func_convert_name <- function( df ) {
  df %>>%
    dplyr::filter( ! str_detect( name, "Suski|Agosto|Yerstein|PRO|12819396952|16177506418|Yakov|SUNY|OBH|Lerner|Kornbluth|tufts|ivia|Grace|Xuemei|iPhone|Ofori|RESPAR|paulgross" ) ) %>>% 
    dplyr::mutate( 
      name = case_when(
        str_detect( name, "ikami" ) ~ "Taka", 
        str_detect( name, "Taka" ) ~ "Taka", 
        str_detect( name, "Valeria" ) ~ "Valeria", 
        str_detect( name, "Firas" ) ~ "Firas", 
        str_detect( name, "asaman" ) ~ "Yasaman", 
        str_detect( name, "asmine" ) ~ "Yasaman", 
        str_detect( name, "anizhe" ) ~ "Manizhe", 
        str_detect( name, "amelia" ) ~ "Camelia", 
        str_detect( name, "afail" ) ~ "Rafail",
        str_detect( name, "vanna" ) ~ "Ivanna",
        str_detect( name, "Aya" ) ~ "Aya",
        str_detect( name, "ikita" ) ~ "Nikita",
        str_detect( name, "aby" ) ~ "Gaby",
        str_detect( name, "hsan" ) ~ "Ehsan",
        str_detect( name, "mniyah" ) ~ "Omniyah",
        str_detect( name, "az" ) ~ "Naz",
        str_detect( name, "arc" ) ~ "Marc",
        str_detect( name, "libay" ) ~ "Alibay",
        str_detect( name, "naman" ) ~ "Naman",
        str_detect( name, "Naman" ) ~ "Naman",
        str_detect( name, "enzheng" ) ~ "Wenzheng",
        str_detect( name, "ustafa" ) ~ "Mustafa",
        str_detect( name, "rsalan" ) ~ "Arsalan",
        TRUE ~ name
      )
    ) 
}

# Tidying files; removed overlapped times 
func_ahd_tidy <- function( filename_i ) { 
  # temp_union = 
  data.table::fread( filename_i ) %>>% 
    dplyr::select( name = 1, t_join = 3, t_leave = 4 ) %>>% 
    func_convert_name() %>>% 
    dplyr::mutate( 
      across( c( t_join, t_leave ), ~ lubridate::mdy_hms(.x) )
    ) %>>% 
    group_by(name) %>%
    mutate(indx = c(0, cumsum(as.numeric(lead(t_join)) >
                                cummax(as.numeric(t_leave)))[-n()])) %>%
    group_by(name, indx) %>%
    summarise(t_join = first(t_join), t_leave = last(t_leave)) %>>% 
    dplyr::ungroup() 
}

func_ahd_ModifyEndTime <- function( i ) { 
  df_leave <- df_ahd_list[[i]] %>>% 
    dplyr::group_by( name ) %>>% 
    dplyr::summarise( max_t_leave = max(t_leave) )
  median_t_leave <- median(sort(df_leave$max_t_leave))
  df_ahd_list[[i]] %>>% 
    dplyr::mutate(
      t_leave = if_else( t_leave > median_t_leave, median_t_leave, t_leave ) ) %>>%
    
    dplyr::mutate( interval = time_length(interval(t_join, t_leave), unit = "minutes") ) %>>% 
    dplyr::arrange(name) %>>%
    dplyr::group_by(name) %>>% 
    dplyr::summarise( 
      t_join = min(t_join), 
      t_leave = max(t_leave),
      t_total = sum(interval), 
      n_login = n()
    ) %>>% 
    dplyr::ungroup() %>>% 
    dplyr::mutate(
      join_rate = t_total / max(t_total)
    ) %>>% 
  dplyr::right_join( df_rotation[c("name", "class", date_list[i])], by = "name" ) %>>% 
    dplyr::rename( rotation = ncol(.) ) %>>% 
    dplyr::mutate( across( t_total:join_rate, ~ replace_na( .x, 0 ) ) )
}
```


```{r Participantce reports}
df_ahd_list <- file_list %>>% lapply( func_ahd_tidy )
df_ahd_list
```


```{r Total participation time}
df_ahd_tidy <- 
  purrr::map_df( 1:4, func_ahd_ModifyEndTime ) %>>% 
  as.data.frame() %>>% 
  dplyr::arrange( name )

df_ahd_tidy$res_id <- as.factor( match(df_ahd_tidy$name, sample(unique(df_ahd_tidy$name))) )
df_rotation_mean <- df_ahd_tidy %>>% 
  dplyr::group_by(rotation) %>>% 
  dplyr::summarise( rate_mean = mean(join_rate) ) %>>% 
  dplyr::arrange( rate_mean )

df_ahd_tidy <- df_ahd_tidy %>>% dplyr::mutate( rotation = fct_relevel( rotation, df_rotation_mean$rotation ) ) 
```


```{r Participation rate for each rotation, echo=FALSE}
df_ahd_tidy %>>% 
  ggplot( aes( x = rotation, y = join_rate, color = class ) ) + 
  geom_point( size = 1.5 ) + 
  labs( 
    title = paste( "Participation rate" ),
    x = "Rotation", 
    y = "Participation (%)" ) + 
  labs( colour = "Residents" ) + # shape="", 
  theme(
    plot.title = element_text(size = 12, hjust = 0, vjust = 3), # , face = "bold"
    legend.justification = c(0, .5), 
    panel.background = element_rect(fill = "white"),
    legend.key  = element_rect(colour = "transparent", fill = "white"),
    legend.text = element_text(size=8),
    legend.title = element_text(size=8), 
    legend.key.height = unit(.3, "cm"), 
    axis.text.x = element_text(angle = 45, hjust =1, size = 10), 
    axis.line.x = element_line(colour = "black", size = .5),
    axis.line.y = element_line(colour = "black", size = .5),
    axis.line = element_line(size = 1
    )
  )
```



```{r The number of login for each rotation, echo=FALSE}
df_plot_login <- df_ahd_tidy %>>% 
  dplyr::group_by( rotation ) %>>%
  dplyr::summarise( n_login = mean(n_login) ) %>>% 
  dplyr::arrange( n_login ) 

df_plot_login %>>% 
  dplyr::mutate( rotation = fct_relevel( rotation, as.vector(df_plot_login$rotation) ) ) %>>%
  ggplot( aes( x = rotation, y = n_login ) ) +
  geom_point( size = 1.5 ) + 
  labs( 
    title = paste( "Login" ),
    x = "Rotation", 
    y = "Number of login" ) + 
  labs( colour = "Residents" ) + # shape="", 
  theme(
    plot.title = element_text(size = 12, hjust = 0, vjust = 3), # , face = "bold"
    legend.justification = c(0, .5), 
    panel.background = element_rect(fill = "white"),
    legend.key  = element_rect(colour = "transparent", fill = "white"),
    legend.text = element_text(size=8),
    legend.title = element_text(size=8), 
    legend.key.height = unit(.3, "cm"), 
    axis.text.x = element_text(angle = 45, hjust =1, size = 10), 
    axis.line.x = element_line(colour = "black", size = .5),
    axis.line.y = element_line(colour = "black", size = .5),
    axis.line = element_line(size = 1
    )
  )
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
